Uk/mobile navbar menu
FortressFinance/ui pull request #24
Opened 2023-02-03 14:54 UTC by orenku

2023-02-03 15:16 UTC, vanillaHill requested changes

2023-02-03 15:16 UTC, vanillaHill commented on src/components/Layout.tsx
> +                    <Menu.Item key={`menu-item-${index}`}>
I think you don't need to add key here too

2023-02-03 15:16 UTC, vanillaHill commented on src/components/Layout.tsx
> +                    key={`menu-item-${index}`}
I think you don't need to add key here

2023-02-03 16:08 UTC, aquaticone requested changes
Would like to give it a test once the preview build is working, but looks good.

2023-02-03 16:08 UTC, aquaticone commented on src/components/Layout.tsx
> +import { RxHamburgerMenu } from "react-icons/Rx"
Lowercase rx and the build will pass

2023-02-03 16:08 UTC, aquaticone commented on src/components/Layout.tsx
> +                    key={`menu-item-${index}`}
Key is needed because it's inside a map

2023-02-05 16:00 UTC, orenku commented on src/components/Layout.tsx
> +                    key={`menu-item-${index}`}
Key is needed because it's inside a map

2023-02-06 14:21 UTC, orenku commented on src/components/Layout.tsx
> +import { RxHamburgerMenu } from "react-icons/Rx"
Fixed

2023-02-14 18:52 UTC, aquaticone requested changes

2023-02-14 18:52 UTC, aquaticone commented on src/components/NetworkSelector.tsx
> +              "text-medium x x inline-flex w-full items-center justify-center space-x-2 rounded-md border-2 bg-black/20 py-1 px-2 text-sm font-medium text-white hover:bg-black/30 md:py-3 md:px-4 md:t
Remove `x x` from here

2023-02-14 19:09 UTC, orenku commented on src/components/NetworkSelector.tsx
> +              "text-medium x x inline-flex w-full items-center justify-center space-x-2 rounded-md border-2 bg-black/20 py-1 px-2 text-sm font-medium text-white hover:bg-black/30 md:py-3 md:px-4 md:t
Where this came from !@?

removed

2023-02-14 19:12 UTC, aquaticone approved these changes

2023-02-14 19:20 UTC, merged