Vanillahill/copy address
FortressFinance/ui pull request #32
Opened 2023-02-07 13:09 UTC by vanillaHill

Closes https://github.com/FortressFinance/issues/issues/82

2023-02-07 21:45 UTC, aquaticone commented
Merge main please and I will review

2023-02-08 20:41 UTC, vanillaHill commented
Merge from main branch done.

2023-02-08 20:49 UTC, aquaticone requested changes

2023-02-08 20:49 UTC, aquaticone commented on src/components/ConnectWallet/ConnectWalletModal.tsx
> +        <div></div>
Is this to create an empty column?

You can use `col-start-2` on the `Dialog.Title` element if you want to skip a column.

2023-02-08 20:49 UTC, aquaticone commented on src/components/ConnectWallet/ConnectWalletModal.tsx
> +  const resetAfterMs = 500
I pulled this down for a test and think this would feel better with 1000ms. What do you think?

2023-02-08 20:49 UTC, aquaticone commented on src/components/ConnectWallet/ConnectWalletModal.tsx
> +            className={clsxm({ "text-green-400": isCopied === true })}
I feel like the green looks a little out of place here, but I'm not sure what would be better. Maybe @galangster has a suggestion?

2023-02-08 23:34 UTC, aquaticone approved these changes

2023-02-08 23:35 UTC, merged