Token Icons - Add missing icons in UI - (excluding YB tokens)
FortressFinance/ui pull request #34
Opened 2023-02-08 10:33 UTC by orenku

This still doesn't include the AuraBal - I will fix it in another PR

2023-02-08 20:47 UTC, vanillaHill commented on src/components/AssetLogo.tsx
> +      case "crypto":
We have only aurabal in crypto now but it won't be the case in the future. It's not a better way to handle the crypto category even if it's working currently imo.

2023-02-08 20:57 UTC, vanillaHill requested changes

2023-02-08 20:57 UTC, vanillaHill commented on src/components/AssetLogo.tsx
> +      case "token":
Normally token no longer exists, replaced by featured/crypto/stable

2023-02-08 20:57 UTC, vanillaHill commented on src/components/MultiLayerTokenLogo.tsx
> +          const top: string = size / 1.5 - 1 + positions[index].x + "px"
You should use variables for these magic numbers, thus the code is easier to read.

2023-02-08 21:22 UTC, aquaticone approved these changes

2023-02-08 21:22 UTC, aquaticone commented on src/components/MultiLayerTokenLogo.tsx
> +      ></BaseLogo>
It's cleaner to self-close tags

```tsx
<BaseLogo ... />
```

2023-02-08 21:22 UTC, aquaticone commented on src/components/MultiLayerTokenLogo.tsx
> +    <span id="mull" className="relative h-8 w-8" style={{ fontSize: 12 }}>
Remove the `id`

2023-02-08 21:22 UTC, aquaticone commented on src/components/TokenForm/TokenSelectModal.tsx
> +                  {" "}
Is this needed?

2023-02-08 21:22 UTC, aquaticone commented on src/components/Vault/VaultDepositForm.tsx
> -            ...(lpTokenOrAsset ? [lpTokenOrAsset ?? "0x"] : []),
Should this be removed?

2023-02-08 21:22 UTC, aquaticone commented on src/hooks/useTokensOrNative.ts
> +  lpToken: Address | Address | undefined
`Address` is here twice

2023-02-08 21:23 UTC, aquaticone requested changes
Pressed approve by accident

2023-02-09 18:02 UTC, orenku commented on next.config.js
> +        pathname: "/FortressFinance/assets/master/blockchains/**",
I'll create a task to be handled in the future

2023-02-09 18:16 UTC, orenku commented on src/components/AssetLogo.tsx
> +  tokenAddress?: `0x${string}`
Fixed

2023-02-09 18:22 UTC, orenku commented on src/hooks/useTokensOrNative.ts
> +  lpToken: Address | Address | undefined
removed

2023-02-10 08:28 UTC, orenku commented on src/components/MultiLayerTokenLogo.tsx
> +    const _positions: { x: number; y: number }[] = []
Just internal variable naming - to differentiate it from the **const positions**  used in the component itself

2023-02-10 08:30 UTC, orenku commented on src/components/AssetLogo.tsx
> +        return <Image src={CurveLogo} priority alt="" />
That repo is a mapping between addresses (token/contract)  to logo
It is not used for general purpose logos such as Curve, Balancer or even Fortress logo

2023-02-10 08:47 UTC, orenku commented on src/components/TokenForm/TokenSelectModal.tsx
> +                  {" "}
No :-)

2023-02-10 08:47 UTC, aquaticone approved these changes

2023-02-10 08:51 UTC, merged